### ISSUE TITLE
Error attempting to initialize communications  with the Optotrak System

### ISSUE THREAD

**Issue by zhengyi0533** [volcic/motom-toolbox#11]
Hi,
I get the OAPI V3.1.6, when I run optotrak_startup, I can't initialize communications with the Optotrak System.

20201015-21:48:49.280 [Err] MessageSystem: Failed sending message header.
20201015-21:49:19.324 [Err] MessageSystem: Failed receiving message preamble.
20201015-21:49:19.324 [Err] OAPI error attempting to initialize communications with the Optotrak System
20201015-21:50:57.909 [Wrn] Structure not initialized (ID = 0, should be 386)
20201015-21:51:10.224 [Sts] Found Camera Parameter Set (1, 0, 0) in Camera C3-07148
20201015-21:51:10.224 [Sts] Found Camera Parameter Set (1, 0, 1) in Camera C3-07148
20201015-21:51:10.224 [Sts] Found Camera Parameter Set (3, 0, 0) in Camera C3-07148
20201015-21:51:10.224 [Sts] Found Camera Parameter Set (3, 0, 1) in Camera C3-07148
20201015-21:51:27.918 [Err] MessageSystem: Failed receiving message preamble.
20201015-21:51:27.918 [Err] OAPI error attempting to initialize communications with the Optotrak System

Thank you!

**Comment by ha5dzs** [comment]
Are you sure you have OAPI 3.1.6? Last time you had OAPI 3.5, which proved to be too old. This is strange. I am assuming you gave me the relevant lines from `OPTO.ERR`.
Have you re-compiled everything by running `RUNME.m`? Just swapping the binaries won't work, unfortunately. If you want to make sure that everything gets re-compiled properly, run `make_mrproper.m`, and then execute `RUNME.m`. This makes sure that the toolbox builds up the shared library objects from the DLL files you copied in.
According to this log output, it can detect your camera (C3-07148). Could you confirm this by deleting `transputer_discovery.log`, re-running `optotrak_startup` again, and check what's inside `transputer_discovery.log`? It should be something like this:
```
Downloading configuration program.
Determining configuration.
Writing system configuration.



Writing camera parameters.

No Errors detected.
System Unit     : present
ODAUs found     : 0

Cameras Found   : C3-07029
                  C3-07027

```

It would also be handy to include the error message from Matlab as well, so I can see where it fails in the code I wrote.

**Comment by zhengyi0533** [comment]
Although I got the new API and recompiled it,  I deleted the toolbox and reset it today. The software I use are matlab 2017A and vs2015. The devices I use are system unit su-07207 and camera c3-07148 3 sensors.
![OAPI](https://user-images.githubusercontent.com/71653166/96224876-d06fec00-0fc2-11eb-8009-630e865b145a.png)
![Optotrak Certus Software](https://user-images.githubusercontent.com/71653166/96224887-d2d24600-0fc2-11eb-9d67-e1430687f7a6.png)
I don't know the firmware version of the device，and if the version is incompatible. I use a USB connection between the SCU and the computer. When I try to update the firmware and software, it tells me that I can't connect to the device. So I didn't update them.
Although I can use the first principle to use the device, it can't be initialized with MATLAB. I put some logs here.
`**In matlab:**
>> optotrak_startup
Warning: The data type 'error#32' used by structure OptoNodeInfoStruct does not exist.  The structure may not be usable. 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The data type 'error#256' used by structure AlignParametersStruct does not exist.  The structure may not be usable. 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The data type 'error#256' used by structure RegisterParametersStruct does not exist.  The structure may not be usable. 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The data type 'error#256' used by structure CalibrigParametersStruct does not exist.  The structure may not be usable. 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The function 'ReadAppParms' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The function 'ReadAppParms_d' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The function 'SaveAppParms' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The function 'SaveAppParms_d' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The function 'DeleteAppParms' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The function 'OptotrakGetApiRev' was not found in the library 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The data type 'FcnPtr' used by function OptoDetermineR does not exist. 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The data type 'FcnPtr' used by function OptoTransformPoint does not exist. 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The data type 'FcnPtr' used by function DetermineR does not exist. 
> In loadlibrary
  In optotrak_startup (line 24) 
Warning: The data type 'FcnPtr' used by function TransformPoint does not exist. 
> In loadlibrary
  In optotrak_startup (line 24) 
The optotrak system says: OAPI error attempting to initialize communications with the Optotrak System
Error using optotrak_startup (line 60)
TransputerInitializeSystem failed. Something must have gone very wrong with the initialisation.

**In transputer_discovery.log**

Downloading configuration program.
Determining configuration.
Writing system configuration.
 
 
 
Writing camera parameters.
 
No Errors detected.
System Unit     : present
ODAUs found     : 0
 
Cameras Found   : C3-07148
**In opto.err**
20201016-14:13:58.600 [Err] MessageSystem: Failed sending message header.
20201016-14:14:28.549 [Err] MessageSystem: Failed receiving message preamble.
20201016-14:14:28.549 [Err] OAPI error attempting to initialize communications with the Optotrak System
`
I have troubled you too much.
Thank you very much!

**Comment by ha5dzs** [comment]
Can I see your `optotrak.ini`? It seems that `TransputerDetermineSystemCfg()` finds your SCU and your camera, but the communication breaks down after them for some reason.

**Comment by zhengyi0533** [comment]
[TLD Info]
realtime =drealtim.tld
admin    =dadmin.tld
sensor   =dsensor.tld
oscope   =oscope2.tld

[OPTOTRAK System]
Driver   =usblink.dll
Driver64 = usblink64.dll
ResetTimeout =1500

[Strober Table]
Port1 =6
Port2 =0
Port3 =0
Port4 =0

[Ethernet Options]
# Server Address=sscu-04030
Server Address=192.168.101.2
Control Port=9999
Data Port=10000
Data Timeout= 4000
Reset Delay=10000

I forgot to tell you that the lights of error and code flash when the matlab program is running.

**Comment by ha5dzs** [comment]
Okay, your `optotrak.ini` looks fine. I just verified our software here, and you have a newer API than what we have! I wasn't aware that they released it, but since as of 15/10/2020, they don't sell this system any more, I am not surprised. I am contacting NDI to get it, but I can't actually try this out in our lab yet, as it is closed due to the pandemic that is raging around.

Anyway, having seen the changes from 3.14 to 3.15, I think you will need a firmware update. However, if you do it, you will lose compatibility with the old Optotrak 3020 (the big rectangular one) cameras. From your `transputer_discovery.log`, I can see that you have a Certus camera connected to your SCU. You still can use the 3020 peripherals on your Certus system with the 3020 adapter, if you have any.

If you don't have any old 3020 cameras and don't plan to use any, please run OptoUpdate and update the firmware.

After doing the firmware update, please add this line again to `optotrak.ini`:
```
Driver64 = usblink64.dll
```
...and try again. I hope it will work.

**Comment by zhengyi0533** [comment]
The sad thing is that it doesn't work.

**Comment by ha5dzs** [comment]
Even after the firmware upgrade?

**Comment by zhengyi0533** [comment]
Yes, the firmware version is 3.15 now.

**Comment by ha5dzs** [comment]
Okay. Can you send me an email? You can get my contact details from the MOTOM toolbox paper. As a temporary solution, I can then send you the 3.15 version of the OAPI, and see if that works. We are using the same firmware here, so assuming there are no other problems, it should work without problems.

Silly question, but the user account on the computer is an administrator, right? This is because the Optotrak system generates some files in `C:\ndigital`, and it can give you cryptic error messages if some file can't be created or written into.

**Comment by zhengyi0533** [comment]
Thank you， I have sent an email to you.
