### ISSUE TITLE
Rigid Bodies

### ISSUE THREAD

**Issue by MfMartel** [volcic/motom-toolbox#4]
Hi,

I'm writing because I am confused about rigid bodies and how to deal with them with the toolbox. In my setup I have 5 markers:

- a head band with a rigid body on it. It is a square with 4 markers, organised exactly in the same order as your fingertip_annotator in the rigid body example list. I created a .rig file with NDI architect, where the origin of the rigid body is the centroid in the middle of the 4 markers

- a marker placed near the mouth of the subject, which is the marker of interest.

Right now, everything is aligned with the camera and I can record the 5 markers. What I would like is to use the moving rigid body as the reference and to get the coordinates of the marker 5 based in reference to the rigid body (as it is possible to do with NDI).

Since the rigid body is dynamic and will be moving during the experiment, I assume I can not just align the system on it, but should rather use the rigid body functions transformations. Or should I do both even though the rigid body is dynamic?

I referred to the example script for `example_rigid_body_handling_with_buffer. Rigid body was successfully loaded, but when I used the commands to transform the data I get results which make no sense: marker 2 (which is a part of the rigid body, and whose signal is good) is written as NaN and the transformed positions seem wrong. Translation is not on the centroid of the rigid body, as it supposed to be according to the wiki (and in my coordinates of the rigid body). I feel like I misunderstood a big point but I cannot figure this out. 

Also, I have a question on real-time: in the case where the real-time loop is slower than the frame rate, and that I don’t have access to all the frames using real-time data, does this mean that there is an issue? For instance my real-time data framecounter is 1*60 double in size, but inside, the value for the column 60 is 1239, which is very close to the 1250 frames I get in the buffered_data. Does this mean that when I plot the real-time data to be sure that I do not lose signal, since the frames are pooled in 60 points, I could miss out a signal loss?

Thank you!

**Comment by ha5dzs** [comment]
Yes, rigid bodies are confusing. We did some updates related to this in the toolbox, please make sure you are using the latest one. All you have to do is to overwrite the toolbox files on your computer, everything should work normally.

To answer things sequentially:
>Since the rigid body is dynamic and will be moving during the experiment, I assume I can not just align the system on it, but should rather use the rigid body functions transformations. Or should I do both even though the rigid body is dynamic?

No, you should use separate rigid bodies for global coordinate system definition and tracking/virtual marker use.

>Translation is not on the centroid of the rigid body, as it supposed to be according to the wiki (and in my coordinates of the rigid body).

It is very important that the rigid body is actually defined correctly. You need to verify that the axes are not rotated or reversed. The Optotrak system can easily return translations that are not possible in real life, but they are mathematically correct. This took me a few months to figure out, so beware. I added an example (`example_virtual_marker_test`) and some documentation about this in the newer version. More on this later.

>Also, I have a question on real-time: in the case where the real-time loop is slower than the frame rate, and that I don’t have access to all the frames using real-time data, does this mean that there is an issue?

I would suggest just simply to use the DataGetLatest* functions as opposed to the DataGetNext* functions. Then you should have the exact same number of data points as your loop iterations, and you might find that your loop will run faster as the DataGetNext* functions block execution for a frame time plus some processing time.

> What I would like is to use the moving rigid body as the reference and to get the coordinates of the marker 5 based in reference to the rigid body (as it is possible to do with NDI).

So, if I understood this right, you want a virtual marker at the mouth that is attached to a rigid body on the participant's forehead, so you could track the position of the mouth without actually attaching a marker to it.

You have two options for doing this.

The first one, which is the simplest, but it only works with one virtual marker is this:
We programmatically create a rigid body file, where the rigid body's local coordinate system's origin coordinates are the virtual marker coordinates. Here is a code for this:
```
% I am assuming that markers 1:4 are the rigid body markers,
% and marker 5 is the mouth marker at the moment of assignment.
marker_coordinates % This vector contains a single row of marker coordinates.

% We now create a rigid body file.
% First argument is the rigid body's marker coordinates (i.e. the 4 markers on the head)
% Second argument is  the origin location of the rigid body's local coordinate system (i. e. mouth)
% Third argument is the output filename
% Fourth argument is the tracking tolerance, in millimetres.
% For more details, check the included help.
optotrak_generate_rigid_body_file(optotrak_get_selected_triplet(1:4, marker_coordinates), optotrak_get_selected_triplet(5, marker_coordinates), 'head_tracker.rig' 2);

% Now we load the rigid body
RigidBodyDelete(0); % Just in case, sometimes loaded rigid bodies can survive a software reset.
RigidBodyAddFromFile_euler(0, 1, 'head_tracker.rig');

% And we get the mouth 'virtual marker' as follows:
[~, ~, translation, ~, marker_coordinates] = DataGetLatestTransforms2_as_array(5);

% The virtual marker coordinates are located in the variable 'translation'.
```

If you want to go the posh way instead, say because you want to attach several virtual markers (nose, ears, etc. in your application) to a rigid body, you can use additional functions provided by the toolbox.

So, after verifying that your rigid body is correctly defined, and that its translation coordinates are indeed the centroid, and that the axes you rotate in is the same one reported by the system and in the same direction as reported by the system, you can can create your virtual marker definition(s) like so:
```
mouth_coordinates; % This is a single X-Y-Z triplet, where the mouth is when the virtual marker is being assigned.
translation; % The head rigid  body's translation coordinates
rotation; % The head rigid body's rotation coordinates

% Now we create the virtual marker definition
% First argument is the virtual marker's initial location
% Second and third arguments are the translation (in this case, it MUST be the centroid) and the rotation
virtual_marker_definition = optotrak_assign_virtual_marker(mouth_coordinates, translation, rotation);
% You can have as many of these as you want

% ...and then, later-on in the experiment, you get the latest rigid body information:
[~, ~, translation, rotation, ~] = DataGetLatestTransforms2_as_array(0);
% ...and you use this to get the virtual marker coordinates:
mouth_virtual_marker_coords = optotrak_get_virtual_marker_coords(virtual_marker_definition, translation, rotation);

% This one works with real-time data, and previously collected frames of data too.
```

I used both methods before in my experiments. The first method is faster as it doesn't require additional number crunching my Matlab, and less error-prone, but doesn't support more than one virtual markers.

**Comment by MfMartel** [comment]
Thank you! I did update the last version, I'll have a look into the `example_virtual_marker_test` to check whether my rigid body is correct. I'm not sure to understand yet how the transformation works, so I'll tell you more on that once I ran some tests.

I actually tried with both DataGetLatest* and DataGetNext* and the result is the same. But I did not have this issue before I started adding the rigid body functions, so maybe I messed up somewhere in the script without noticing. Because before I had one command giving me directly the 1239 frames in positions, and the other one giving me a way bigger number (I assumed because of the speed of the loop and duplication of the data). And since I'm only using the real-time loop to check the marker signal during the experiment, I was wondering whether this number was important in my case.

And actually, no I also have a marker attach on the mouth, but the idea was that instead of having global coordinates that do not mean much, we would have as a reference the forehead. If for instance the baby moves its head down, then in global coordinates, the mouth marker is going to be lower, but in reality the distance will still be the same with the forehead suggesting that the mouth stayed closed (we are interested in mouth movements during eating/speaking) so we need to be able to see if the mouth really moved, or if it was the whole head. I thought that using the rigid body transformation would allow that without having to manually calculate the distances. Does it make sense?

**Comment by ha5dzs** [comment]
Good luck with the rigid bodies!

The difference between DataGetNext* and DataGetLatest* is that the former one forces a new data acquisition sequence from the system, and the latter returns the one already at hand. Since you have a very small difference between the loop speed and the frame rate, I would thing you will have an aliasing effect if you use DataGetNext*. As a rule of thumb, I just use DataGetLatest* and a higher sampling rate, unless I need something specific.

Re the rigid body on the forehead, you can use `optotrak_get_distance()` to read the distance between the rigid body's translation coordinates and the mouth marker. If you map the virtual marker to the mouth marker when idle, you will have a very neat way of measuring the relative displacement of the mouth.

**Comment by MfMartel** [comment]
I checked and even with DataGetLatest, I have a `realtime.framecounter` of 1*58 double but a buffered_data of 1250 frames. Which is weird because before, I did not have these numbers at all. I checked the script and copy and pasted from examples but it doesn't seem to change anything.
What could be the reason for such sudden pooling of the data? My frame frequency is 125Hz.

Also, am I assuming correctly that if I use your technique for assigning the virtual marker, then I need to do that for each participant to be sure that the coordinates are correct? If so, then it might not be the best solution because since we are testing babies, we want the experiment to start as fast as possible once they have the markers on.
But then, I guess I can use `optotrak_get_distance()` to get the distance between the marker 5 and the centroid of my rigid body. I don't even need to load the rigid body, if I manage to calculate the coordinates of the centroid. I guess I could create a virtual marker as the centroid of my 4 markers on the head. Does it make sense?
Is it something I can calculate afterwards, once I have all the data? Maybe it would be easier to record the 5 markers in global coordinates, and then I calculate the centroid of the 4 markers, and the distance to marker 5?

**Comment by ha5dzs** [comment]
> What could be the reason for such sudden pooling of the data? My frame frequency is 125Hz.  

I am not sure if I understand this. You are using real-time data, but you are also doing buffering too? Can you copy and paste your config file and provide a skeleton loop of your experiment code (you can strip it down as much as you like) so I can see what you are doing? Because if you are getting 58 frames of data in your loop, you really shouldn't be getting 1250 frames of coordinates, especially since you are getting the framecounter with the 3D coordinates with the same operation. But it is totally possible to buffer 1250 frames, and only sampling 58 of them as real-time data.

> Also, am I assuming correctly that if I use your technique for assigning the virtual marker, then I need to do that for each participant to be sure that the coordinates are correct? If so, then it might not be the best solution because since we are testing babies, we want the experiment to start as fast as possible once they have the markers on.  

This really depends on your experimental design and application. It literally takes a single frame of data to make the rigid body file, and about 100 milliseconds for the rigid body file to be loaded. I am relying on generating my rigid bodies and virtual markers in my fingertip tracking application for each and every participant at the beginning of my experiment. But I also made hardware which I made before I started the study, and I just load them during the initialisation part of my code.

> I don't even need to load the rigid body, if I manage to calculate the coordinates of the centroid.  

Of course, you can calculate everything manually. The advantage of using the rigid body is that it always returns the same coordinates, even if not all markers are visible. For example, in your case, if you lose one head marker, the centroid calculation would give a bad location, and would ruin your data.

> Is it something I can calculate afterwards, once I have all the data? Maybe it would be easier to record the 5 markers in global coordinates, and then I calculate the centroid of the 4 markers, and the distance to marker 5?

This also depends on your experimental set-up and application. If you save raw data with the toolbox, you can convert it to 3D coordinates with or without rigid bodies. Not only that, but depending on what camera file you use, you can change the global coordinate system too. This is why it's worthwhile buffering, and then converting the raw data afterwards. While you do this, you still can monitor the real-time data (using DataGetLatest*). Of course, this comes at a compromise of you having to record for the entire collection time you have specified in the config file. You theoretically can also change the collection time during a session with the `OptotrakSetupCollection()` API function, but I never used it because it takes a ton of arguments.

**Comment by MfMartel** [comment]
> I am not sure if I understand this. You are using real-time data, but you are also doing buffering too? Can you copy and paste your config file and provide a skeleton loop of your experiment code (you can strip it down as much as you like) so I can see what you are doing? Because if you are getting 58 frames of data in your loop, you really shouldn't be getting 1250 frames of coordinates, especially since you are getting the framecounter with the 3D coordinates with the same operation. But it is totally possible to buffer 1250 frames, and only sampling 58 of them as real-time data.

I use a similar structure as `example_advanced_experiment` with the experimental loop and the realtime loop. So at the end I have both real time data and buffered data. My understanding was that with the real time loop I could monitor my signal online and make sure that I don't lose markers during trials. But I am using the buffered data for my analyses.
I am not getting 58 frames of data but, I am getting a 1*58 matrice with the data pooled and for instance: 

```
- real_time_data.trial_1.framecounter(1) = 0
- real_time_data.trial_1.framecounter(2) = 101
- real_time_data.trial_1.framecounter(3) = 141
- [...]
- real_time_data.trial_1.framecounter(58) = 1241 which is very close to the 1250 frames, so I think the data is just pooled together, but I have no idea why
```

Here is my config file:

```
- [OPTOTRAK System]
- NumberOfMarkers = 5
- FrameFrequency = 125
- MarkerFrequency = 1750
- DutyCycle = 0.5
- StroberVoltage = 7
- InterpolationFlag = TRUE
- NoFireMarkers = FALSE
- StaticThresholdFlag = FALSE
- StaticThresholdValue = 0
- DynamicThresholdPercent = 30
- MinimumGain = 160
- CollectionTime = 10
- PreTriggerTime = 0
- StreamData = 0
- DynamicDutyFlag = FALSE
- BufferWaveformsFlag = FALSE
- Buffer3dFlag = FALSE
- BufferFullRawFlag = FALSE
- GetNextFrameFlag = FALSE
- ExternalSyncFlag = FALSE
- ExternalTriggerFlag = FALSE
- PollRealDataFlag = FALSE
- bConvertOnHost = TRUE
- bRigidOnHost = TRUE
- MarkerType = 3
- WavelengthType = 0
- ModelType = 1
- TimeOut = 5
- bIgnoreVersionCheck = FALSE
- bPerformExpectedSystemCheck = FALSE
- bmode = 0
- RCParam1 = 0
- RCParam2 = 1
- 3dErrorMode = 1
```

And here is the loop:

```
for(i = 1:number_of_trials)
    
    %test for marker activation
    [TestMarker, marker_coords] = optotrak_get_marker_coords(1);
    if TestMarker == -1 %Markers not activated
        OptotrakActivateMarkers()
        fprintf('Markers Activated.\n')
    else fprintf('Markers Already Activated.\n')
    end
 
    %Experimental loop
    sound(signal, fs); %play a sound
    fprintf('Trial %d begins, ', i)
    DataBufferInitializeFile(0, temp_data_file); % 0 means we are collecting data from the Optotrak
    fprintf('data buffer now initialised.\n')

    record(recObj); %Start audio recording !!! You don't hear the bip in the audio !!!
    DataBufferStart; %This starts the actual recording
    %Bounce up the framecounter before going to the real-time loop.
    [~, ~, ~, ~] = DataGetLatest3D_as_array;

    fprintf('RECORDING NOW! This will take %d seconds.\n', data_acquisition_settings.collection_time);
    %While we are buffering, we can have access to the real-time data.
    recording_trial = 1; %This is a flag for the real-time loop to execute
    trial_frame_pointer = 1; %This variable is used to fill-in the arrays
    
    while(recording_trial)
        %real-time loop.
       
        %Within this loop, you can handle real-time data. 
        tic; %measure time as well.
        
        %If this loop executes slower than the frame rate, use this:
        [fail, real_time_data.(sprintf('trial_%d', i)).framecounter(trial_frame_pointer), real_time_data.(sprintf('trial_%d', i)).positions(trial_frame_pointer, :), ~ ] = DataGetLatest3D_as_array;
        %If this loop executes faster than the frame rate, use this:
        %[fail, real_time_data.(sprintf('trial_%d', i)).framecounter(trial_frame_pointer), real_time_data.(sprintf('trial_%d', i)).positions(trial_frame_pointer, :), ~ ] = DataGetNext3D_as_array;
         
        real_time_data.(sprintf('trial_%d', i)).execution_time(trial_frame_pointer) = toc; %This is for perfomance checking. You won't need this.
        
        %Calculate how many frames are we skipping
        frame_skip = round(mean(diff( real_time_data.(sprintf('trial_%d', i)).framecounter ))); 
        
        %Get the online position of the markers to check for data loss
        optotrak_plot_marker_positions(squeeze(real_time_data.(sprintf('trial_%d', i)).positions(:,:,:)))

        %have we finished the trial?
        if(real_time_data.(sprintf('trial_%d', i)).framecounter(trial_frame_pointer)  >= ((number_of_frames_per_trial * i) - frame_skip) )
            %If we got here, it means that the system has collected enough
            %frames for a single trial
            recording_trial = 0;
        else
            % if not, keep in the loop.
        
            trial_frame_pointer = trial_frame_pointer + 1; %Offset this pointer by one.
        end
        
        
    end

    %Once the buffer finished, we can 'spool' the data from the buffer into
    %the temporary file.
    optotrak_stop_buffering_and_write_out;
    fprintf('Recording ended.\n')
    %Stop audio recording
    stop(recObj);
    
    % Now we need to convert the raw data to positions. We also save it to
    % a structure, nice and neat.
    [ fail, buffered_data.(sprintf('Trial_%d', i)) ] = optotrak_convert_raw_file_to_position3d_array(temp_data_file);
    if(fail)
        %Assuming the file is intact, you should never get here.
        optotrak_tell_me_what_went_wrong; %This writes out the last error message from the system
        error('Couldn''t convert the raw data file to positions.')
    end
    
    %Deactivate the markers
    OptotrakDeActivateMarkers()
    
    %Save sound in .wav
    y = getaudiodata(recObj);
    %plot(y);
    audioname = strcat('audio', '_', 'sub', (sujet), '_sess', (session), '_', sprintf('Trial_%d', i), '_', (date), '.wav');
    cd (directory)
    audiowrite(audioname, y, fs)
    cd ..\..\..
 
    pause(2);
    
end
```

**Comment by MfMartel** [comment]
As for the rigid bodies

> This really depends on your experimental design and application. It literally takes a single frame of data to make the rigid body file, and about 100 milliseconds for the rigid body file to be loaded. I am relying on generating my rigid bodies and virtual markers in my fingertip tracking application for each and every participant at the beginning of my experiment. But I also made hardware which I made before I started the study, and I just load them during the initialisation part of my code.

I see your point, somehow I thought that it was longer because it took some time to make the .rig on NDI architect. Here, I would always use this file but just adjust the distance for each subject, am I correct?

I'm going to try with your solution. I have to admit, I don't think I entirely got how rigid body transformation works. Still need to try and see what it does with the virtual_marker example you added in the toolbox.

**Comment by ha5dzs** [comment]
Okay, I took a look at your code and explanation.

The `framecounter` variable is just a serial number of the frame you just downloaded using `DataGetLatest3D_as_array()`. So what you see is perfectly fine, your loop's 58th iteration just hapened to be frame number 1241. Ideally, your `real_time_data.(sprintf('trial_%d', i)).positions(2, :)` should be the same as `buffered_data.(sprintf('Trial_%d', i))(101, :)`. (so your second real-time coordinates should correspond with the 101st buffered coordinates in the example you showed me)

Why do you save the real-time data as well as the buffered data?  
Are you using this real-time loop of yours to check performance, where the timing reference is the Optotrak system's framecounter?

You could just simply measure time with Matlab's `tic` and `toc`, the timing tolerance is much less than 1/125 Hz. Then your real-time loop can be much simpler, as you just need one exit semaphore.

Re rigid bodies, yep, they are confusing, and it took me several weeks to wrap my head around them. I think this is pretty much the best feature of this system, and I use it literally all the time.

**Comment by MfMartel** [comment]
> The framecounter variable is just a serial number of the frame you just downloaded using DataGetLatest3D_as_array(). So what you see is perfectly fine, your loop's 58th iteration just hapened to be frame number 1241. Ideally, your real_time_data.(sprintf('trial_%d', i)).positions(2, :) should be the same as buffered_data.(sprintf('Trial_%d', i))(101, :). (so your second real-time coordinates should correspond with the 101st buffered coordinates in the example you showed me)

I see, great then, thank you!

> Why do you save the real-time data as well as the buffered data?
Are you using this real-time loop of yours to check performance, where the timing reference is the Optotrak system's framecounter?

I'm using the loop to plot the online position of the marker, and monitor them during the trials (those are long trials lasting several minutes, with babies, so we have to make sure we see the markers at any point). But I'm not using the real time data for anything else. Is there an easiest way to reduce the loop?

> You could just simply measure time with Matlab's tic and toc, the timing tolerance is much less than 1/125 Hz. Then your real-time loop can be much simpler, as you just need one exit semaphore.

Uhm, not sure I understand what you mean...

**Comment by ha5dzs** [comment]
So, you could reduce your real-time loop to something like this:
```
% You can use optotrak_get_setup_info() to get this this
collection_time = 10; % in seconds, 
number_of_markers = 4; % pieces :)
trial_is_on = 1
loop_iteration_counter = 1;
tic; % Start Matlab's timer.
while(trial_is_on)
    % Assuming you have the rigid body loaded:
    [~, framecounter, translations, ~, marker_data] = DataGetLatestTransforms2_as_array(number_of_markers);

    % You can do something else in the loop here, like testing marker proximity, visualisation, etc
    optotrak_plot_marker_positions(marker_data, 'Here are the markers');

    % Are we finished yet?
    trial_time = toc; % Get Matlab's internal timestamp
    if(trial_time > collection_time)
       % If we spent enough time here, terminate the loop at the next iteration
        trial_is_on = 0;
    else
        loop_iteration_counter = loop_iteration_counter + 1;
    end
end
fprintf('Trial is over, the loop was executed %d times.\n', loop_iteration_counter);
```
If this loop operates too fast, you will get the same data using `DataGetLatest*` multiple times. This is not a problem. If you want to see marker traces as well as the latest location, use this line instead:
```
[~, framecounter(loop_iteration_counter), translations(loop_iteration_counter, :), ~, marker_data(loop_iteration_counter, :)] = DataGetLatestTransforms2_as_array(number_of_markers);
```
If you want your virtual marker's data to be plotted like this, just concatenate it accordingly.

**Comment by MfMartel** [comment]
Hi,

So I’ve tested several scripts for rigid bodies. Here’s where I’m at:

First, just to be sure, the recorded buffered data is the raw data, without any transformation, even if we add a rigid body in the mix, right? And then you get the transformed data in the "translation" variable. Am I correct?


Last time you wrote:
> The first one, which is the simplest, but it only works with one virtual marker is this:
> We programmatically create a rigid body file, where the rigid body's local coordinate system's origin coordinates are the virtual marker coordinates. Here is a code for this:
> 
> ```
> % I am assuming that markers 1:4 are the rigid body markers,
> % and marker 5 is the mouth marker at the moment of assignment.
> marker_coordinates % This vector contains a single row of marker coordinates.
> 
> % We now create a rigid body file.
> % First argument is the rigid body's marker coordinates (i.e. the 4 markers on the head)
> % Second argument is  the origin location of the rigid body's local coordinate system (i. e. mouth)
> % Third argument is the output filename
> % Fourth argument is the tracking tolerance, in millimetres.
> % For more details, check the included help.
> optotrak_generate_rigid_body_file(optotrak_get_selected_triplet(1:4, marker_coordinates), optotrak_get_selected_triplet(5, marker_coordinates), 'head_tracker.rig' 2);
> 
> % Now we load the rigid body
> RigidBodyDelete(0); % Just in case, sometimes loaded rigid bodies can survive a software reset.
> RigidBodyAddFromFile_euler(0, 1, 'head_tracker.rig');
> 
> % And we get the mouth 'virtual marker' as follows:
> [~, ~, translation, ~, marker_coordinates] = DataGetLatestTransforms2_as_array(5);
> 
> % The virtual marker coordinates are located in the variable 'translation'.
> ```

To get `marker_coordinates ` I recorded 50 frames of the markers position and then calculated the mean so I have an 1*N array.
My current rigid body, that I made with NDI Architect doesn't seem to work: the translations values are NaN when I run this `[~, ~, translation, ~, marker_coordinates] = DataGetLatestTransforms2_as_array(5);`

Here is a picture of it: https://ibb.co/XyPGbVY

If I try to create the rigid body with the command you wrote, then I have an issue with `optotrak_generate_rigid_body_file(optotrak_get_selected_triplet(1:4, marker_coordinates), optotrak_get_selected_triplet(5, marker_coordinates), 'head_tracker.rig', 2);` because the normal_vector_coordinates are missing, and I don’t know what to put in there. In the help it is indicated that 

> normal_vector_coordinates is a 1-by-N array. The normal vectors are perpendicular to the marker's plane.
> %       If unsure, just give it a bunch of zeros.
> %       For simple rigid bodies, all normal vectors can point to the same direction
> %       Also, since this is a normal vector the length of the vector must be 1.

If we compare the 2 functions
`optotrak_generate_rigid_body_file(optotrak_get_selected_triplet(1:4, marker_coordinates), optotrak_get_selected_triplet(5, marker_coordinates), 'head_tracker.rig', 2);` 
 `optotrak_generate_rigid_body_file(coordinates, origin_marker, filename, coordinate_tolerance, normal_vector_coordinates, varargin)`, **coordinates**  is equal here to only 4 markers, so I guess I need to put 4 **normal_vector_coordinates** and not 5.

I tried with normal_vector_coordinates = [0,0,0,0]. But then I have an error 
```
Error using optotrak_generate_rigid_body_file (line 73)
Marker normal vector coordinates must be in X-Y-Z triplets.
```

So I tried with triplets (I put 0,0,1 the same way you specified it in the optotrak_generate_rigid_body_file function since my plan is constituted with X and Y and Z is perpendicular to it)
normal_vector_coordinates = [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1]; and then I have an error about 
```
Operands to the || and && operators must be convertible to logical scalar values.

Error in optotrak_generate_rigid_body_file_4markers (line 93)
    if(origin_marker < 1 || origin_marker > (length(coordinates)/3) )
```

And I have no clue where the issue comes from...


I also tested the example_virtual_marker_test, but I am confused by the use of `[virtual_marker_definition] = optotrak_assign_virtual_marker(virtual_marker_coords, centroid_coordinates, rotation)` (in your script you did it manually).

- for **virtual_marker_coords** I guess I have to use the recorded data from the mouth `optotrak_get_selected_triplet(5, marker_coordinates)`
- for **centroid_coordinates** I am a bit more unsure on how to get the centroid of my Rigid body. Should I use the `optotrak_calculate_centroid_and_orientation.m` function ? It is written in the help that it is for one marker, and not 4...
- for **rotation**, I have no clue...

Thanks!

**Comment by ha5dzs** [comment]
If you get a bunch of NaNs instead of your rigid body transforms, it mens that the rigid body transform was unsuccessful. This could be due to a number of reasons (not enough visible markers, too much spread, transform tolerance too high, etc.), and since the Optotrak system doesn't provide any useful error messages about this, it's difficult to debug unfortunately. You might want to check this with `optotrak_tell_me_what_went_wrong()` or by reading the log files in the `ndigital` directory. My bet is that something is wrong with the created rigid body file.

Re the normal vectors, I suffered a lot with this one, and found out that they don't seem to make any difference in tracking whatsoever, and since there is next to nothing included about it in the decade-old documentation I have, I decided to get rid of them in `optotrak_generate_rigid_body_file()`. This is why I asked to make sure that you have the newest version of the toolbox, because this is one of the things I have changed. I changed the code and its documentation, but I forgot about the example. 

I think your issue comes from that you are trying to adapt the `example_rigid_body_creation` example that is now broken because of this.

I will update the example (and the corresponding wiki, because now that I checked it seems that the change didn't propagate for some reason) as well, when I am back from annual leave. Until then, you can refer to `help <function_name>` within the toolbox as I am updating the documentation inside the file as I am updating the code.
I have added an example below on how to get this to work. I will calculate the centroid, so the translation coordinates will be the centroid.

Let's say that the mean coordinates are stored in `marker_positions`, which is a 1-by-12 array (one frame, 4 XYZ triplets). You can calculate the centroid with this:
```
centroid_coordinate = optotrak_calculate_centroid_and_orientation(marker_positions);
```
If you have these, you can create the rigid body file:
```
optotrak_generate_rigid_body_file(marker_positions, centroid_coordinate, 'head_rigid_body.rig', 2);
```
Then, you can load the rigid body file as usual, and get the translation and rotation coordinates. this will work fine with `optotrak_assign_virtual_marker()`.

If you substitute `centroid_coordinate` with a different position (i.e. the mouth at resting state), then the returned translation coordinates will be the virtual marker that is always at a fixed location with respect to the rigid body, wherever it may be in the global coordinate system.

I used both methods in my experiments, they work fine.

Hope this helps!

**Comment by MfMartel** [comment]
> Re the normal vectors, I suffered a lot with this one, and found out that they don't seem to make any difference in tracking whatsoever, and since there is next to nothing included about it in the decade-old documentation I have, I decided to get rid of them in `optotrak_generate_rigid_body_file()`. This is why I asked to make sure that you have the newest version of the toolbox, because this is one of the things I have changed. I changed the code and its documentation, but I forgot about the example.

You're right, jeez that's stupid, sorry! Guess I forgot to copy/paste some folders.

I did not find anything particular with `optotrak_tell_me_what_went_wrong()` but without the normal vector issues, I managed to create a rigid body with your scripts. I checked the .rig file and it is very similar to the one I had using NDI Architect; so who knows what happened.

I've decided to use the centroid coordinate to create the rigid body.

So now, just to be sure that I understand things correctly. In my experiment

- I load the rigid body

- Since I am using `[~, framecounter, translation, rotation, marker_data] = DataGetLatestTransforms2_as_array(data_acquisition_settings.number_of_markers);` to check the signal of my markers, at the end I have `translation` and `rotation` variables with just 1 row of value each (I guess for the last frame). This is supposed to be the translation and rotation of the defined rigid body but I honestly have trouble to really get the meaning of this. Does this mean that when applying this translation and rotation to each marker, you get the centroid coordinates?

- With the function `optotrak_convert_raw_file_to_rigid_euler_array()` I am supposed to get the transformed data? Does this mean that it should be the coordinates of all my markers based on the centroid? And for instance, instead of having global coordinates, I will have something that tells me that the marker on the mouth is + 15cm from the centroid in one direction? Weirdly, here, I get the exact same data with this command and `optotrak_convert_raw_file_to_position3d_array()` which is supposed to ignore the rigid body transformation. Could this mean that even if I had no error to build the rigid body, something went wrong?


Thanks

**Comment by ha5dzs** [comment]
Okay, this looks good.

Re the usage of `DataGetLatestTransforms2_as_array()`, yes, this is precisely how it works. If you define the centroid as the origin of the rigid body's local coordinate system, the `translation` coordinates will be the centroid's coordinates.

Re `optotrak_convert_raw_file_to_rigid_euler_array()`, you can get the marker data and the transform data as well. However, it only works on a properly initialised system (i.e. load your correct camera and rigid body files prior to executing this). If you execute `optotrak_convert_raw_file_to_position3d_array()` the results are identical, except that the system doesn't do the rigid body transforms so you have to calculate the centroid's coordinate yourself.
In your case, where you defined the centroid as the translation coordinates, you will need to create a virtual marker where the mouth is at resting state. Then, you can calculate the relative displacement of the mouth with respect to the rigid body on the head.

And to answer this question specifically:
>Could this mean that even if I had no error to build the rigid body, something went wrong?

The rigid body transform expresses the positions defined in the rigid body's local coordinate system in the global coordinate system. So all coordinates you ever get from this are in the global coordinate system. In your case, the centroid coordinates should not correspond with any of the markers.

**Comment by MfMartel** [comment]
Okay, I think I'm finally starting to get my head around this. Thank you!

So this means that if I want to test whether my rigid body works fine, I can just put my marker 5 in the centroid position and then the translation coordinates and the marker 5 coordinates should be the same, am I right?

> In your case, where you defined the centroid as the translation coordinates, you will need to create a virtual marker where the mouth is at resting state. Then, you can calculate the relative displacement of the mouth with respect to the rigid body on the head.

Ok, this is the part I still don't get... Why do I need a virtual marker on the mouth if I have my marker 5 already on the mouth? If I define a virtual marker on the resting state position of the mouth (let's say when the mouth is closed), the position will be constant at all time. Am I correct? Does this mean that I actually need this virtual marker so then I can compute the distance between the real marker 5 and the virtual marker 5 to get the mouth displacement? Isn't it enough to just calculate the distance between the centroid and the real marker 5? I'm not sure I see the interest of this virtual marker...

**Comment by ha5dzs** [comment]
> So this means that if I want to test whether my rigid body works fine, I can just put my marker 5 in the centroid position and then the translation coordinates and the marker 5 coordinates should be the same, am I right?

Yes, exactly! :)

> Does this mean that I actually need this virtual marker so then I can compute the distance between the real marker 5 and the virtual marker 5 to get the mouth displacement?

I think this is the case of me over-thinking your problem, sorry about that. I thought that you want to know where the mouth was at resting state with respect to the forehead, and you want to measure the relative location of the mouth over time with respect to the forehead.  If that's not the case, and you just want to use the rigid bodies, then you don't need to make your life unnecessarily complicated with virtual markers.

**Comment by MfMartel** [comment]
Great!

> I think this is the case of me over-thinking your problem, sorry about that. I thought that you want to know where the mouth was at resting state with respect to the forehead, and you want to measure the relative location of the mouth over time with respect to the forehead. If that's not the case, and you just want to use the rigid bodies, then you don't need to make your life unnecessarily complicated with virtual markers.

Well I do want to measure the relative location of the mouth over time with respect to the forehead, but I managed to get it with `optotrak_get_distance()`; the mouth being limited in the opening/closing, I get the resting state position in between 2 opening/closing cycles.
I think that's enough for now. But thanks for all the explanation on the virtual markers :)
