### ISSUE TITLE
Adapt collection time for each trial

### ISSUE THREAD

**Issue by ghost** [volcic/motom-toolbox#5]
Hi, 
I am starting to use the motom toolbox. I am wondering whether it is possible to change the collection time for each trial. Indeed I have two type trials of different time lenght but I am struggling to find a solution to record those trials with timing I expect.
Best,
Simon

**Comment by ha5dzs** [comment]
Hi,

Zoltan here.

Unfortunately the Optotrak system doesn't support that directly. If you really need to use the data buffer, the closest equivalent would be to use the `OptotrakSetupCollection()` API function, which allows you to change the data collection time on the fly. You need to know your collection time in advance, as spooling the data from the buffer prematurely before the collection time elapses will corrupt your data. I circumvented this in two ways in my experiments:

- If you must use buffering, record for the longest time you are expecting. There is a whopping 6 megabytes of RAM in the SCU, and you will get a warning if you are about to fill it when calling `optotrak_set_up_system()`.

- If you use the system below 100 Hz frame rate, use streaming (`DataGetLatest* and DataGetNext*` functions) and just simply not get any more frames from the system when you are done. You will have problems with keeping up timing in your loop, but the framecounter value will help you see if you had any dropped frames.

If these don't suit you and you really want to go the `OptotrakSetupCollection()` way, the function is available in the toolbox. You will see that it's very fiddly, especially when it comes to the hardware flags. Perhaps the easiest would be to get the system working with a config file initially, then call `OptotrakGetStatus()` to get all the current settings, change the collection time, and then call `OptotrakSetupCollection()`.  But I haven't used this in a live experiment, so make sure you test your set-up thoroughly.

Hope this helps!

**Comment by ghost** [comment]
Hi Zoltan, 

Thanks for your quick reply. 

Finally we decided to keep
a constant collection time through trials making issue easier to solve.


However, I have a totally different issue not related to the first
one. Indeed, I get ".dat" file for each trials but I think something is
going wrong with the encoding format because I get a file only with
symbols once I open it with excel or word. I am using the function
optotrak_convert_raw_file_to_position3d_array and thus I am wondering
wether I have to specify a format encoding for my data file before to
use this function or if I am currently doing something wrong with this
function. 

Best wishes, 

Simon

Le 2019-09-24 21:47, Zoltan Derzsi a
écrit :

> Hi, 
> 
> Zoltan here. 
> 
> Unfortunately the Optotrak
system doesn't support that directly. If you really need to use the data
buffer, the closest equivalent would be to use the
OptotrakSetupCollection() API function, which allows you to change the
data collection time on the fly. You need to know your collection time
in advance, as spooling the data from the buffer prematurely before the
collection time elapses will corrupt your data. I circumvented this in
two ways in my experiments: 
> 
> * 
> 
> If you must use buffering,
record for the longest time you are expecting. There is a whopping 6
megabytes of RAM in the SCU, and you will get a warning if you are about
to fill it when calling optotrak_set_up_system(). 
> * 
> 
> If you use
the system below 100 Hz frame rate, use streaming (DataGetLatest* and
DataGetNext* functions) and just simply not get any more frames from the
system when you are done. You will have problems with keeping up timing
in your loop, but the framecounter value will help you see if you had
any dropped frames. 
> 
> If these don't suit you and you really want to
go the OptotrakSetupCollection() way, the function is available in the
toolbox. You will see that it's very fiddly, especially when it comes to
the hardware flags. Perhaps the easiest would be to get the system
working with a config file initially, then call OptotrakGetStatus() to
get all the current settings, change the collection time, and then call
OptotrakSetupCollection(). But I haven't used this in a live experiment,
so make sure you test your set-up thoroughly. 
> 
> Hope this helps! 
>

> --
> You are receiving this because you authored the thread.
> Reply
to this email directly, view it on GitHub [1], or mute the thread [2].



Links:
------
[1]
https://github.com/volcic/motom-toolbox/issues/5?email_source=notifications&amp;email_token=AK5ECAHUIGUQUGFICRYP4MLQLJVETA5CNFSM4I2CYUS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7PSV2Q#issuecomment-534719210
[2]

**Comment by ha5dzs** [comment]
The raw data files are not coordinates unfortunately, they are just a bunch of numbers. For each frame, each sensor (within each camera) and each marker, the system stores one number, which is the maximum intensity position on the CCD of the sensors. Optionally, you can also save the intensity value as well in the raw data. Optotrak uses linear addressing on each the 2D sensors inside the camera. So opening the raw data file on its own is not very useful, unless you want to get some information in the header. There are API functions for that, like `FileRead()`.

To convert the raw data file to positions you can see in Matlab, you need to have the system properly initialised and and call `optotrak_convert_raw_file_to_position3d_array()`. This can be done immediately after a trial, so you don't need to reset the system for that. If you have a rigid body loaded, you can use `optotrak_convert_raw_file_to_rigid_euler_array()`, which gets you the rigid body transforms AND the marker data as well.

While this looks complicated at first glance, it is quite useful: if you made a mistake during calibration or loaded the wrong rigid body file, you can re-process the raw data and still get the correct coordinates out. 

Provided that the spooling was not interrupted prematurely, the raw data file should not be corrupt, and the conversion should be possible. There is only one file format for this, Optotrak's own, and if it doesn't work, `optotrak_convert_raw_file_to_position3d_array()` should give you some meaningful error messages about it. 

So what I do is I save the raw data file, convert the raw data to a Matlab position array, and then I save my data as a .csv file inside my experimental loop.

**Comment by ghost** [comment]
Hi Zoltan, 

Thank you for your reply. 

Sorry for this silly question.
I was thinking optotrak_convert_raw_file_to_position3d_array() was able
to convert and save data in the same time. Sorry for this
misunderstanding. 

Almost everything is working fine. However, I have
new issue. I would like to record 8 markers. I did all my tests with 6
markers, thus I changed the .ini file with the parameter NumberOfMarkers
from 6 to 8. However it does not work with 8 and work perfectly by
keeping 6. I got this error message in the case 8 is chosen : 

The
optotrak system says: Optotrak: Failed sending collection
parameters.
Error using optotrak_set_up_system (line
35)
OptotrakSetupCollectionFromFile() failed. Check opto.err for
details. 

Error in SyntaxUnder (line
28)
optotrak_set_up_system(camera_file, config_file); 

I don't know
where to find the mentionned opto.err file, moreover all my markers seem
to be correctly plugged. I also tried to change NumbersOfMarkers in
optotrak.ini file but it did not change something for this issue. 

Do
you have any idea about what is wrong ? 

Best, 

Simon 

Le 2019-09-25
14:03, Zoltan Derzsi a écrit :

> The raw data files are not coordinates
unfortunately, they are just a bunch of numbers. For each frame, each
sensor (within each camera) and each marker, the system stores one
number, which is the maximum intensity position on the CCD of the
sensors. Optionally, you can also save the intensity value as well in
the raw data. Optotrak uses linear addressing on each the 2D sensors
inside the camera. So opening the raw data file on its own is not very
useful, unless you want to get some information in the header. There are
API functions for that, like FileRead(). 
> 
> To convert the raw data
file to positions you can see in Matlab, you need to have the system
properly initialised and and call
optotrak_convert_raw_file_to_position3d_array(). This can be done
immediately after a trial, so you don't need to reset the system for
that. If you have a rigid body loaded, you can use
optotrak_convert_raw_file_to_rigid_euler_array(), which gets you the
rigid body transforms AND the marker data as well. 
> 
> While this
looks complicated at first glance, it is quite useful: if you made a
mistake during calibration or loaded the wrong rigid body file, you can
re-process the raw data and still get the correct coordinates out. 
> 
>
Provided that the spooling was not interrupted prematurely, the raw data
file should not be corrupt, and the conversion should be possible. There
is only one file format for this, Optotrak's own, and if it doesn't
work, optotrak_convert_raw_file_to_position3d_array() should give you
some meaningful error messages about it. 
> 
> So what I do is I save
the raw data file, convert the raw data to a Matlab position array, and
then I save my data as a .csv file inside my experimental loop. 
> 
>
--
> You are receiving this because you authored the thread.
> Reply to
this email directly, view it on GitHub [1], or mute the thread [2].



Links:
------
[1]
https://github.com/volcic/motom-toolbox/issues/5?email_source=notifications&amp;email_token=AK5ECAASD3GU236G33AIST3QLNHP5A5CNFSM4I2CYUS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7RUP6Y#issuecomment-534988795
[2]

**Comment by ha5dzs** [comment]
By the looks of it, if `optotrak_tell_me_what_went_wrong()` says that the collection settings were not uploaded successfully, I would suspect that something is wrong with the config file. If all you did is to increase the number of markers, I would check whether the marker frequency is high enough. It could well be that with the current marker frequency and current number of markers (and the extra time offset), it would take more time to flash all markers in sequence than what the frame frequency would allow. This is detailed in the original Optotrak documentation, but I usually use the following formula to get started:
```
frame_frequency = (marker_frequency) / (number_of_markers + 2)
```
The file `opto.err` file is located in `c:\ndigital\logs`, provided that you used the default path during  installation, and you use Windows.

**Comment by ghost** [comment]
Hi Zoltan, 

Thank you for your help, everything seems to work fine.

Best, 

Simon

 

De : Zoltan Derzsi <notifications@github.com> 
Envoyé : vendredi 27 septembre 2019 12:28
À : volcic/motom-toolbox <motom-toolbox@noreply.github.com>
Cc : simthi <simon.thibault@inserm.fr>; Author <author@noreply.github.com>
Objet : Re: [volcic/motom-toolbox] Adapt collection time for each trial (#5)

 

By the looks of it, if optotrak_tell_me_what_went_wrong() says that the collection settings were not uploaded successfully, I would suspect that something is wrong with the config file. If all you did is to increase the number of markers, I would check whether the marker frequency is high enough. It could well be that with the current marker frequency and current number of markers (and the extra time offset), it would take more time to flash all markers in sequence than what the frame frequency would allow. This is detailed in the origina Optotrak documentation, but I usually use the following formula to get started:

frame_frequency = (marker_frequency) / (number_of_markers + 2)

The file opto.err file is located in c:\ndigital\logs, provided that you used the default path during installation, and you use Windows.
